name: sentry_mobile
description: Sentry Mobile App

publish_to: "none"

version: 1.1.0+37

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ^3.3.10

dependencies:
  clipboard: ^0.1.3
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.2
  flutter_redux: ^0.10.0
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^1.1.6
  google_fonts: ^4.0.3
  http: ^0.13.3
  in_app_review: ^2.0.2
  intl: ^0.18.0
  json_annotation: ^4.0.1
  qr_code_scanner: ^1.0.1
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  sentry_flutter: ^6.19.0
  shared_preferences: ^2.0.6
  timeago: ^3.1.0
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter_icons:
  image_path: "assets/logo.png"
  ios: true

flutter:
  uses-material-design: true

  fonts:
   - family: SentryIcons
     fonts:
       - asset: assets/fonts/SentryIcons.ttf

  assets:
    - assets/sentry_eula_android.md
    - assets/sentry_eula_ios.md
    - assets/user-menu.png
    - assets/sitting-logo.jpg
    - assets/reading-logo.jpg
    - assets/onboarding_1_a.png
    - assets/onboarding_1_b.png
    - assets/onboarding_2.png
    - assets/onboarding_3.png
    - assets/platformicons/
