# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	# Defined in Appfile
	app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
	team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

	desc "Bump the build number"
	lane :bump do
		increment_build_number(
			xcodeproj: './Runner.xcodeproj',
  			build_number: latest_testflight_build_number + 1
		)
	end

	desc "Build ipa"
	lane :build do |options|
		update_code_signing_settings(
			use_automatic_signing: false,
			path: "./Runner.xcodeproj",
			targets: ["Runner"]
		)
		gym(
			output_directory: "./build",
			output_name: "sentry-mobile-ios",
			include_bitcode: false,
			include_symbols: true,
			xcargs: { # https://github.com/fastlane/fastlane/issues/12849#issuecomment-404978983
				:BUNDLE_IDENTIFIER => app_identifier,
				:PROVISIONING_PROFILE_SPECIFIER => "#{ENV['FASTLANE_PROVISIONING_PROFILE_NAME']}",
				:DEVELOPMENT_TEAM => team_id,
				:CODE_SIGN_IDENTITY => "iPhone Distribution"
			},
			export_options: {
				method: "app-store",
				provisioningProfiles: { 
					app_identifier => "#{ENV['FASTLANE_PROVISIONING_PROFILE_NAME']}",
				}
			}
		)
		update_code_signing_settings(
			use_automatic_signing: true,
			path: "./Runner.xcodeproj",
			targets: ["Runner"]
		)
	end

	desc "Upload ipa to TestFlight"
	lane :upload do |options|
		pilot(
			ipa: "build/sentry-mobile-ios.ipa",
			distribute_external: false,
			skip_waiting_for_build_processing: true
		)
	end
end
