# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

	before_all do |lane, options|
		# Fetch API key before running any other lane
		app_store_connect_api_key(
			key_id: ENV['APPSTORE_CONNECT_API_KEY_ID'],
			issuer_id: ENV['APPSTORE_CONNECT_API_ISSUER_ID'],
			key_content: ENV['APPSTORE_CONNECT_API_AUTH_KEY'],
		)
	end

	desc "Bump the build number"
	lane :bump do
		increment_build_number(
			xcodeproj: './Runner.xcodeproj',
  			build_number: latest_testflight_build_number + 1
		)
	end

	desc "Build ipa"
	lane :build do |options|
		gym(
			output_directory: "./build",
			output_name: "sentry-mobile-ios",
			include_bitcode: false,
			include_symbols: true,
			export_options: {
			method: "app-store",
				provisioningProfiles: { 
					"#{ENV['APP_BUNDLE_ID']}" => "#{ENV['APP_PROVISIONING_PROFILE_NAME']}",
				}
			}
		)
	end

	desc "Upload ipa to TestFlight"
	lane :upload do |options|
		pilot(
			ipa: "build/sentry-mobile-ios.ipa",
			distribute_external: false,
			skip_waiting_for_build_processing: true
		)
	end
end
