import 'package:flutter_svg/svg.dart';

// ignore: avoid_classes_with_only_static_members
class PlatformIcons {
  // Source: https://github.com/getsentry/platformicons/blob/master/src/platformIcon.tsx
  static final platformToFileName = <String, String>{
    'android': 'android',
    'apple': 'apple',
    'apple-ios': 'apple',
    'clojure': 'clojure',
    'cocoa': 'apple',
    'cocoa-objc': 'apple',
    'cocoa-swift': 'swift',
    'cordova': 'cordova',
    'cryengine': 'cryengine',
    'csharp': 'csharp',
    'csharp-aspnetcore': 'csharp',
    'dart': 'dart',
    'default': 'default',
    'dotnet': 'dotnet',
    'dotnet-awslambda': 'aws',
    'dotnet-aspnetcore': 'dotnet',
    'dotnet-aspnet': 'dotnet',
    'dotnet-csharp': 'csharp',
    'dotnet-blazor': 'blazor',
    'dotnet-uno': 'uno',
    'dotnet-xamarin': 'xamarin',
    'dotnetcore': 'dotnetcore',
    'dotnetfx': 'dotnetfx',
    'electron': 'electron',
    'elixir': 'elixir',
    'flutter': 'flutter',
    'fsharp': 'fsharp',
    'go': 'go',
    'godot': 'godot',
    'java': 'java',
    'java-appengine': 'app-engine',
    'java-android': 'android',
    'java-log4j': 'java',
    'java-log4j2': 'java',
    'java-logback': 'logback',
    'java-logging': 'java',
    'java-spring': 'spring',
    'java-spring-boot': 'springboot',
    'javascript': 'javascript',
    'javascript-angular': 'angularjs',
    'javascript-angularjs': 'angularjs',
    'javascript-backbone': 'backbone',
    'javascript-browser': 'javascript',
    'javascript-cordova': 'cordova',
    'javascript-electron': 'electron',
    'javascript-ember': 'ember',
    'javascript-gatsby': 'gatsby',
    'javascript-nextjs': 'nextjs',
    'javascript-react': 'react',
    'javascript-vue': 'vue',
    'kotlin': 'kotlin',
    'kotlin-android': 'android',
    'native': 'nativec',
    'node': 'nodejs',
    'node-awslambda': 'aws',
    'node-azurefunctions': 'azure',
    'node-connect': 'nodejs',
    'node-express': 'express',
    'node-gcpfunctions': 'gcp',
    'node-koa': 'koa',
    'perl': 'perl',
    'php': 'php',
    'php-laravel': 'laravel',
    'php-monolog': 'php',
    'php-symfony2': 'symfony',
    'php-symfony': 'symfony',
    'python': 'python',
    'python-aiohttp': 'aiohttp',
    'python-awslambda': 'aws',
    'python-azurefunctions': 'azure',
    'python-bottle': 'bottle',
    'python-celery': 'celery',
    'python-chalice': 'chalice',
    'python-django': 'django',
    'python-falcon': 'falcon',
    'python-flask': 'flask',
    'python-gcpfunctions': 'gcp',
    'python-pylons': 'python',
    'python-pyramid': 'pyramid',
    'python-pythonawslambda': 'aws',
    'python-rq': 'redis',
    'python-sanic': 'python',
    'python-serverless': 'serverless',
    'python-tornado': 'tornado',
    'python-tryton': 'tryton',
    'qt': 'qt',
    'react-native': 'react',
    'ruby': 'ruby',
    'ruby-rack': 'ruby',
    'ruby-rails': 'rails',
    'ruby-sinatra': 'sinatra',
    'rust': 'rust',
    'rust-actix': 'actix',
    'scala': 'scala',
    'stride3d': 'stride3d',
    'swift': 'swift',
    'unity': 'unity',
    'unreal': 'unreal',
    // Don't add new platforms down here!
    // Please add them where they belong alphabetically
  };

  static SvgPicture svgPicture(String platform) {
    final filename = platformToFileName[platform];
    if (filename != null) {
      return SvgPicture.asset('assets/platformicons/$filename.svg', width: 24, height: 24
      );
    } else {
      return null;
    }
  }
}
