/// Flutter icons SentryIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SentryIcons
///      fonts:
///       - asset: fonts/SentryIcons.ttf
///
/// 
///



import 'package:flutter/widgets.dart';

class SentryIcons {
  SentryIcons._();

  static const _kFontFam = 'SentryIcons';
  static const String? _kFontPkg = null;

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_up = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_down = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData issues = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trend_same = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
